---
- name: Disable SELinux for testing ease
  lineinfile:
    dest:   /etc/selinux/config
    regexp: "^SELINUX=.*"
    line:   "SELINUX=disabled"
  become: yes 
  when: common_centos_selinux_enabled == false

- name: EPEL Repo check
  command: yum list installed epel-release
  register: epel_check
  failed_when: epel_check.rc > 1
  when: common_centos_repo_epel_enabled

- name: Install EPEL repo
  yum:  name=epel-release state=latest update_cache=yes
  when:
    - common_centos_repo_epel_enabled
    - epel_check.rc == 1

- name: RPMFusion Repo check
  command: yum list installed rpmforge-release
  register: rpm_check
  failed_when: rpm_check.rc > 1
  when: common_centos_repo_rpmfusion_enabled

- name: RPMFusion Repo
  yum:  name={{ item }}
        state=present
        update_cache=yes
        validate_certs=false
  with_items:
    - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm
  when:
    - common_centos_repo_rpmfusion_enabled
    - rpm_check.rc == 1

- name: Install common packages
  yum:  pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git
    - wget
    - nfs-utils
#    - nfs-utils-lib
    - zip
    - unzip
    - python-pip
  become: yes

  - name: Disable IPV6
    lineinfile:
      path: /etc/sysctl.conf
      line: "net.ipv6.conf.all.disable_ipv6 = 1"
      regexp: "^net.ipv6.conf.all.disable_ipv6*"
      create: yes
      insertafter: EOF
    become: yes
    when: not common_centos_ipv6_enabled